/**
 * @author              : Raju Vegesna
 * @description         : Constants can be used across the ORG
 * @created             : July 2020
 * @created by          : Gravitai
 * @last modified       : Aug 2020
 * @last modified by    : Raju Vegesna
 **/

public class Constants {
  /*  Record Types    */
  // public static final String RT_LEA_PERSON_REFERRAL = 'SPW Person Referral';
  public static final String RT_ACC_BUSINESS = 'Business';
  public static final String RT_ACC_HOUSEHOLD = 'Household';
  public static final String RT_ACC_PERSON_ACCOUNT = 'Person Account';
  // public static final String RT_OPP_HOLISTIC_ADVICE = 'Holistic advice';
  public static final String RT_OPP_FOCUSED_ADVICE = 'Focused advice  (OAR, TAR, Topups)';
  public static final String RT_COMPLAINT = 'Complaint';
  public static final String RT_S_T_Investments = 'S_T_Investments';
  public static final String RT_S_T_Pensions = 'S_T_Pensions';
  public static final String SLA_COMPLAINT = 'SPW Complaint Support Process';
  public static final String SLA_S_T_Investments = 'SPW Switches & Transfers Investments Process';
  public static final String SLA_S_T_Pensions = 'SPW Switches & Transfers Pensions Process';
  public static final String COMPLAINT_PROCESS = 'Complaint';
  public static final String INVESTMENT_PROCESS = 'Investments';
  public static final String PENSION_PROCESS = 'Pensions';
  public static final String CASE_STATUS_NEW = 'New';
  public static final String CASE_STATUS_CLOSED = 'Closed';
  public static final String CASE_STATUS_ESCALATED = 'Escalated';
  public static final String CASE_STATUS_VOID = 'Void';
  public static final String CASE_STATUS_INPROGRESS = 'In Progress';
  public static final String CASE_TRANSACT = 'Transact';
  public static final String ENTITLEMENT_COMPLAINT_SUPPORT = 'Complaint Support';
  public static final String LEAD_STATUS_NEW = 'New';
  public static final String LEAD_STATUS_IN_PROG = 'In Progress';
  public static final String LEAD_STATUS_NURTURING = 'Nurturing';
  public static final String LEAD_STATUS_UNQUALIFIED = 'Unqualified';
  public static final String LEAD_STATUS_CONVERTED = 'Converted';
  public static final String LEAD_LOSS_REASON_NOT_INTERESTED = 'Not interested in investing';
  public static final String TASK_SPW_TRANSACT = 'SPW_Transact';
  public static final String RT_RR_ACCOUNT_ROLE = 'Account Role';
    public static final String RT_RR_CONTACT_ROLE = 'Contact Role';

  // PROFILE NAMES
  public static final String SYS_ADMIN_PROFILE = 'System Administrator';
  public static final String SPW_COMPLIANCE_PROFILE = 'SPW Compliance Team';
  public static final String SPW_PWA_PROFILE = 'SPW Personal Wealth Advisor';

  // ORG Names in CMT
  public static final String SPW_PROD_ORG = 'PROD';
    
 // Constants for Transact Cases
 public static final String CASE_TRANSACT_WITHDRAWAL= 'Withdrawal'; 
 public static final String TRANSACT_CALLBACK_UNDERTAKEN='Callback_Undertaken';
 public static final String TRANSACT_PLAUSIBILITY='Transact_Plausibility';
 public static final String TRANSACT_SECURITY_GIA='Transact_Security_GIA';
 public static final String TRANSACT_ADVICE_TIMESCALES='Transact_Advice_Timescales';
 public static final String TRANSACT_CONFIRMED_BANK_ACC='Transact_confirmed_bank_account';
 public static final String TRANSACT_STRATEGY_CHANGE_REG_WITHDRAWAL='Strategy_Change_Regular_Withdrawal';
 public static final String TRANSACT_STRATEGY_CHANGE= 'Strategy Change';
 
}
